config/routes.rb
Rails.application.routes.draw do

  devise_for :shot_geeks
  get 'shots/notes' => 'shots#notes'

  resources :shots

  root 'shots#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :shot
  belongs_to :shot_geek
end

app/models/shot.rb
class Shot < ActiveRecord::Base
  has_many :notes
  has_many :shot_geeks, through: :notes
  accepts_nested_attributes_for :notes, :allow_destroy => true
  def moyenne
    notes.map{|note| note.value}.sum / notes.size unless notes.empty?
  end

end

app/models/shot_geek.rb
class ShotGeek < ActiveRecord::Base
    has_many :notes
    has_many :shots, through: :notes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  before_action :set_shot, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_shot_geek!,except: [:index, :show]


  # GET /shots
  # GET /shots.json
  def index
    @shots = Shot.all
  end

  # GET /shots/1
  # GET /shots/1.json
  def show
  end

  # GET /shots/new
  def new
    @shot = Shot.new
  end

  # GET /shots/1/edit
  def edit
  end


  # POST /shots
  # POST /shots.json
  def create
    @shot = Shot.new(shot_params)

    respond_to do |format|
      if @shot.save
        format.html { redirect_to @shot, notice: 'Shot was successfully created.' }
        format.json { render :show, status: :created, location: @shot }
      else
        format.html { render :new }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shots/1
  # PATCH/PUT /shots/1.json
  def update
    respond_to do |format|
      if @shot.update(shot_params)
        format.html { redirect_to @shot, notice: 'Shot was successfully updated.' }
        format.json { render :show, status: :ok, location: @shot }
      else
        format.html { render :edit }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shots/1
  # DELETE /shots/1.json
  def destroy
    @shot.destroy
    respond_to do |format|
      format.html { redirect_to shots_url, notice: 'Shot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shot
      @shot = Shot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shot_params
      params.require(:shot).permit(:name, :description, :notes_attributes => [:value, :id, :shot_geek, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>INF4041</title>
  <%= stylesheet_link_tag    'application.css.scss', media:'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/shots/_form.html.erb
<%= semantic_form_for @shot do |f| %>
  <% if @shot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shot.errors.count, "error") %> prohibited this shot from being saved:</h2>

      <ul>
      <% @shot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.inputs do %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.semantic_fields_for :notes do |notes_form| %>
            Note: <%= notes_form.text_field :value %>
            <%= notes_form.check_box :_destroy %>
            <%= notes_form.hidden_field :shot_geek_id, value: current_shot_geek.id %>
        <% end %>
    <% end %>

    <%= f.actions do %>
        <%= f.action :submit, :as => :button %>
    <% end %>
<% end %>

app/views/shots/edit.html.erb
<h1>Editing shot</h1>

<%= render 'form' %>

<%= link_to 'Show', @shot %> |
<%= link_to 'Back', shots_path %>

app/views/shots/index.html.haml
%h1 Liste des shots

%table
  %thead
    %tr
      %th Nom
      %th Description
      %th Note
      %th{colspan: 3}
  - @shots.each do |shot|
    %tr
      %td= shot.name
      %td= shot.description
      %td= shot.moyenne
      %td= link_to 'Voir', shot
      %td= link_to 'Modifier', edit_shot_path(shot)
      %td= link_to 'Détruire', shot, method: :delete, data: { confirm: 'Are you sure?' }

app/views/shots/new.html.erb
<h1>New shot</h1>

<%= render 'form' %>

<%= link_to 'Back', shots_path %>

app/views/shots/notes.html.haml
%h1 Liste des notes

%table
  %thead
    %tr
      %th Note
  - @shots.each do |shot|
    %tr
      %td= shot.note

%p
  Moyenne :
  %span= @moyenne

app/views/shots/show.html.haml
%p
%strong Name:
= @shot.name
%p
%strong Description:
= @shot.description
%p
%strong Notes:
%br
- @shot.shot_geeks.each do |shot_geek|
  %span=shot_geek.email
  %span a attribué la note
  - shot_geek.notes.each do |note|
    %span=note.value


  %br
= link_to 'Edit', edit_shot_path(@shot)
|
\#{link_to 'Back', shots_path}